### ISSUE TITLE
Renaming distribution files

### ISSUE THREAD

**Issue by hgouraud** [geneweb/geneweb-plugin-v7#2]
Je renommerais les fichiers de la distrib geneweb-commitgw-plugin-commitplugin

**Comment by sagotch** [comment]
Pourquoi pas. Peu importe pour l'instant, donc on peut le changer effectiement, mais à un moment il faudra peut-etre nommer les fichiers selon une regle defini par geneweb (a definir) afin de faciliter la gestion des plugins.

Tu peux donc changer.

EDIT: C'est dans le appveyor.yml, mais attention a tout changer comme il faut et a eviter de pusher trop souvent car le build met super longtemps a se faire sur appveyor et ça bloque les autres
